version: '3.4'

networks:
  blazingportfolionetwork:
    external:
      name: blazingportfolionetwork

services:
  blazingportfolio:
    image: ${DOCKER_REGISTRY-}blazingportfolio
    build:
      context: .
      dockerfile: BlazingPortfolio/Dockerfile
    networks:
      - blazingportfolionetwork 
  cosmosdb:
    container_name: cosmosdb
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    tty: true
    restart: always
    ports:
      - "8081:8081"
      - "8900:8900"
      - "8901:8901"
      - "8979:8979"
      - "10250:10250"
      - "10251:10251"
      - "10252:10252"
      - "10253:10253"
      - "10254:10254"
      - "10255:10255"
      - "10256:10256"
      - "10350:10350"