name: Build and depoy the blazingportfolio frontend

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: sossenbinder
          password: ${{ secrets.BLAZOR_PUSH_GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./BlazingPortfolio
          file: ./BlazingPortfolio/Dockerfile
          push: true
          tags: sossenbinder/blazingportfolio

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull sossenbinder/blazingportfolio
            docker rm --force blazingportfolio
            docker run -d --name blazingportfolio --network nginxproxy -v /etc/letsencrypt/:/certs sossenbinder/blazingportfolio
